name: ltotest

permissions:
  contents: write  
  actions: write   

on:
  workflow_call: 
    inputs:
      codename:
        required: true
        type: string
      repo:
        required: true
        type: string

jobs:
  ltotest:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Install LLVM and build tools
        run: |
         sudo apt update
         sudo apt install -y \
         gcc-13 g++-13 \
         binutils gcc-aarch64-linux-gnu \
         make curl git libssl-dev flex bison libelf-dev \
         libncurses-dev ccache

      - name: Set environment variables
        run: |
          echo "CC=aarch64-linux-gnu-gcc-13" >> $GITHUB_ENV
          echo "LD=aarch64-linux-gnu-ld" >> $GITHUB_ENV
          echo "AR=aarch64-linux-gnu-ar" >> $GITHUB_ENV
          echo "NM=aarch64-linux-gnu-nm" >> $GITHUB_ENV
          echo "OBJCOPY=aarch64-linux-gnu-objcopy" >> $GITHUB_ENV
          echo "OBJDUMP=aarch64-linux-gnu-objdump" >> $GITHUB_ENV
          echo "STRIP=aarch64-linux-gnu-strip" >> $GITHUB_ENV
          echo "CONFIG=${{ inputs.repo }}" >> $GITHUB_ENV


      - name: Clone AnyKernel3 and Kernel Source
        run: |
          git clone --depth=1 https://github.com/spanish33/AnyKernel3.git -b 15.0.0-sultan-zuma
          git clone --depth=1 https://github.com/spanish33/${{ inputs.repo }} -b sultan-susfs

         
      - name: Add KernelSU
        run: |
          cd "${{ env.CONFIG }}"
          curl -LSs "https://raw.githubusercontent.com/spanish33/kernelsu/main/kernel/setup.sh" | bash -
     
      - name: Apply SUSFS and LTO
        run: |
          cd "${{ env.CONFIG }}"
          DEFCONFIG=arch/arm64/configs/${{ inputs.codename }}_defconfig
              
          echo "CONFIG_KSU=y" >> $DEFCONFIG
          echo "CONFIG_KSU_WITH_KPROBES=n" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> $DEFCONFIG
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> $DEFCONFIG
          echo "CONFIG_TMPFS_XATTR=y" >> $DEFCONFIG
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> $DEFCONFIG
          echo "# CONFIG_BCM7038_L1_IRQ is not set" >> $DEFCONFIG
          echo "# CONFIG_ARCH_BRCMSTB is not set" >> $DEFCONFIG
          echo "CONFIG_LTO=y" >> $DEFCONFIG
          echo "# CONFIG_LTO_NONE is not set" >> $DEFCONFIG
          echo "# CONFIG_LTO_CLANG is not set" >> $DEFCONFIG
          
      - name: Change Kernel Name
        run: |
          echo "Changing to configuration directory: $CONFIG..."
          cd "${{ env.CONFIG }}"
          
          echo "Changing Kernel Name..."
          sed -i 's/CONFIG_LOCALVERSION="-Sultan"/CONFIG_LOCALVERSION="-android14-11-gd7dac4b14270-ab12946699"/' ./arch/arm64/configs/${{ inputs.codename }}_defconfig

      - name: Build the Kernel
        run: |
          cd "${{ env.CONFIG }}"
          make O=out ARCH=arm64 ${{ inputs.codename }}_defconfig
          make O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc --all)

      - name: Inspect vmlinux for LTO sections
        run: |
         cd "${{ env.CONFIG }}/out"
         if [ -f vmlinux ]; then
         echo "== readelf .gnu.lto_ section check =="
         readelf -S vmlinux | grep '\.gnu\.lto_' || echo "❌ No .gnu.lto_ sections found."
         else
         echo "❌ vmlinux not found!"
         fi

      - name: Check .config for LTO options
        run: |
         cd "${{ env.CONFIG }}/out"
         grep -E "CONFIG_LTO|CONFIG_THINLTO|CONFIG_LTO_GCC|CONFIG_LTO_CLANG" .config
         grep "CONFIG_LTO" .config
         
      - name: Copy Images
        run: |
          cd "${{ env.CONFIG }}"
          cp out/arch/arm64/boot/Image.lz4 ../AnyKernel3/Image.lz4
          cat out/google-devices/zuma/dts/*.dtb > ../AnyKernel3/dtb

      - name: Create Flashable ZIP
        run: |
          cd AnyKernel3
          ZIP_NAME="${{ inputs.codename }}_ltotest_${{ github.sha }}.zip"
          zip -r "../$ZIP_NAME" ./*

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-${{ inputs.codename }}
          path: |
            ./${{ inputs.codename }}_ltotest_*.zip
